root 21196 0.0 0.0 13320 3212 pts/3 S+ 10:20 0:00 bash get_linux_logs.sh root 21293 0.0 0.0 13320 3152 pts/3 S+ 10:20 0:00 bash get_linux_logs.sh root 21298 0.0 0.0 13320 1848 pts/3 S+ 10:20 0:00 bash get_linux_logs.sh root 21300 0.0 0.0 14864 2548 pts/3 S+ 10:20 0:00 grep get_linux_logs.sh
4
Logging script already running
root 21196 0.0 0.0 13320 3244 pts/3 S 10:20 0:00 bash get_linux_logs.sh root 23331 0.0 0.0 13320 3232 pts/3 S+ 10:31 0:00 bash get_linux_logs.sh root 23336 0.0 0.0 13320 1776 pts/3 S+ 10:31 0:00 bash get_linux_logs.sh root 23338 0.0 0.0 14864 2532 pts/3 S+ 10:31 0:00 grep get_linux_logs.sh
4
Logging script already running
root 21196 0.0 0.0 13320 3244 pts/3 S 10:20 0:00 bash get_linux_logs.sh root 23356 0.0 0.0 13320 3072 pts/3 S+ 10:32 0:00 bash get_linux_logs.sh root 23361 0.0 0.0 13320 1656 pts/3 S+ 10:32 0:00 bash get_linux_logs.sh root 23363 0.0 0.0 14864 2520 pts/3 S+ 10:32 0:00 grep get_linux_logs.sh
4
Logging script already running
INFO:     Will watch for changes in these directories: ['/server_resource/log_server_resources']
ERROR:    [Errno 98] Address already in use
INFO:     Will watch for changes in these directories: ['/server_resource/log_server_resources']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [24296] using watchgod
INFO:     Started server process [24298]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     144.48.135.25:26054 - "GET / HTTP/1.1" 200 OK
root 21196 0.0 0.0 13320 3244 pts/3 S 10:20 0:00 bash get_linux_logs.sh root 24316 0.0 0.0 13320 3152 pts/5 S 10:37 0:00 bash get_linux_logs.sh root 24321 0.0 0.0 13320 1824 pts/5 S 10:37 0:00 bash get_linux_logs.sh root 24323 0.0 0.0 14864 2552 pts/5 S 10:37 0:00 grep get_linux_logs.sh
4
Logging script already running
INFO:     144.48.135.25:26054 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     144.48.135.25:26054 - "GET /docs HTTP/1.1" 200 OK
INFO:     144.48.135.25:26054 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     144.48.135.25:26055 - "GET /get_logs HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 124, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data
httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered
WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 124, in data_received
    self.parser.feed_data(data)
  File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data
httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered
INFO:     144.48.135.25:27113 - "GET /get_logs HTTP/1.1" 200 OK
WARNING:  WatchGodReload detected file change in '['/server_resource/log_server_resources/main.py']'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [24298]
INFO:     Started server process [25045]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Will watch for changes in these directories: ['/server_resource/log_server_resources']
ERROR:    [Errno 98] Address already in use
INFO:     Will watch for changes in these directories: ['/server_resource/log_server_resources']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [25162] using watchgod
INFO:     Started server process [25164]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     144.48.135.25:23939 - "GET /docs HTTP/1.1" 200 OK
INFO:     144.48.135.25:23939 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     144.48.135.25:23939 - "GET /get_logs HTTP/1.1" 200 OK
['shared', 'free', 'core_1', 'used', 'core_0', 'core_3', 'core_2', 'total', 'available', 'buff/cache']
INFO:     144.48.135.25:23940 - "GET /GetGraph/serverLogs_2022_04_07.log HTTP/1.1" 200 OK
WARNING:  WatchGodReload detected file change in '['/server_resource/log_server_resources/main.py']'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [25164]
INFO:     Started server process [25620]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     144.48.135.25:25126 - "GET /docs HTTP/1.1" 200 OK
INFO:     144.48.135.25:25126 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     144.48.135.25:25126 - "GET /get_logs HTTP/1.1" 200 OK
['used', 'buff/cache', 'core_3', 'available', 'core_2', 'free', 'core_1', 'shared', 'core_0', 'total']
INFO:     144.48.135.25:25127 - "GET /GetGraph/serverLogs_2022_04_07.log HTTP/1.1" 200 OK
INFO:     18.206.246.18:15108 - "GET /docs HTTP/1.1" 200 OK
INFO:     182.186.90.201:50935 - "GET /docs HTTP/1.1" 200 OK
INFO:     182.186.90.201:50934 - "GET /openapi.json HTTP/1.1" 200 OK
['used', 'buff/cache', 'core_3', 'available', 'core_2', 'free', 'core_1', 'shared', 'core_0', 'total']
INFO:     144.48.135.25:23903 - "GET /GetGraph/serverLogs_2022_04_07.log HTTP/1.1" 200 OK
INFO:     144.48.135.25:23966 - "GET /get_logs HTTP/1.1" 200 OK
INFO:     119.158.38.210:7844 - "GET /docs HTTP/1.1" 200 OK
INFO:     119.158.38.210:7844 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     119.158.38.210:7846 - "GET /docs HTTP/1.1" 200 OK
INFO:     119.158.38.210:7846 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     119.158.38.210:7847 - "GET / HTTP/1.1" 200 OK
4
Logging script already running
INFO:     119.158.38.210:7847 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     119.158.38.210:7848 - "GET / HTTP/1.1" 200 OK
4
Logging script already running
INFO:     182.186.90.201:50964 - "GET /get_logs HTTP/1.1" 200 OK
['used', 'buff/cache', 'core_3', 'available', 'core_2', 'free', 'core_1', 'shared', 'core_0', 'total']
INFO:     182.186.90.201:50969 - "GET /GetGraph/serverLogs_2022_04_07.log HTTP/1.1" 200 OK
INFO:     182.186.90.201:50970 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     182.186.90.201:51068 - "GET /get_logs HTTP/1.1" 200 OK
INFO:     119.115.21.169:51964 - "POST /editBlackAndWhiteList HTTP/1.1" 404 Not Found
INFO:     128.1.248.42:46396 - "GET /admin/ HTTP/1.1" 404 Not Found
INFO:     203.135.47.116:58269 - "GET /docs HTTP/1.1" 200 OK
INFO:     203.135.47.116:39802 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     203.135.47.116:15449 - "GET /get_logs HTTP/1.1" 200 OK
INFO:     203.135.47.116:62974 - "GET /GetGraph/serverLogs_2022_04_07.log HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
   INFO:     Will watch for changes in these directories: ['/mnt/volume_blr1_01/server_resource/log_server_resources']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12087] using watchgod
INFO:     Started server process [12089]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     144.48.135.25:26681 - "GET /docs HTTP/1.1" 200 OK
INFO:     144.48.135.25:26681 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     144.48.135.25:26681 - "GET /get_logs HTTP/1.1" 200 OK
INFO:     144.48.135.25:26682 - "GET /docs HTTP/1.1" 200 OK
INFO:     144.48.135.25:26682 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     144.48.135.25:26682 - "GET /GetGraph/serverLogs_2022_04_07.log HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/volume_blr1_01/server_resource/log_server_resources/./main.py", line 26, in GetGraph
    df = pd.read_csv(file_name, sep = "\t")
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1254, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/root/anaconda3/envs/resource/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 805, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 8 fields in line 1826, saw 14

WARNING:  WatchGodReload detected file change in '['/mnt/volume_blr1_01/server_resource/log_server_resources/main.py']'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12089]
INFO:     Started server process [14294]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchGodReload detected file change in '['/mnt/volume_blr1_01/server_resource/log_server_resources/main.py']'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14294]
INFO:     Started server process [14309]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchGodReload detected file change in '['/mnt/volume_blr1_01/server_resource/log_server_resources/main.py']'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14309]
WARNING:  WatchGodReload detected file change in '['/mnt/volume_blr1_01/server_resource/log_server_resources/main.py']'. Reloading...
INFO:     Started server process [14326]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     144.48.135.25:23796 - "GET /docs HTTP/1.1" 200 OK
INFO:     144.48.135.25:23796 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     144.48.135.25:23796 - "GET /get_logs HTTP/1.1" 200 OK
['core_0', 'total', 'core_1', 'free', 'available', 'core_2', 'core_3', 'used', 'buff/cache', 'shared']
INFO:     144.48.135.25:23795 - "GET /GetGraph/serverLogs_2022_04_07.log HTTP/1.1" 200 OK
